backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# This line should *not* be indented
publish_mode: editorial_workflow
# This line should *not* be indented
media_folder: "public/static/images" # Media files will be stored in the repo under static/images
public_folder: "/public/static/images" # The src attribute for uploaded media will begin with /images
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    extension: mdx
    format: frontmatter
    label: "Blog" # Used in the UI
    folder: "data/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.mdx
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "nametags"}
      - {label: "Description", name: "summary", widget: "description"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Authors", name: "authors", widget: "author"}
      - {label: "Body", name: "body", widget: "markdown"}